name: first-actions
on:
  push:
    branches:
      - 'master'
jobs:
  run-the-deployment-sh-file:
    runs-on: ubuntu-latest
    steps:
      - run: echo this is a test common without repo checkout.
